---
title: "Density descriptives"
format: html
editor: visual
---

## 

```{r}
#| echo: false
#| include: false

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/1.setup_import.r")

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/2.prep_riskfactors.r")

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/3.prep_casummary.r")

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/4.prep_detectionmode.r")

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/5.prep_mammodensity.r")

source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/6.cr_mammodensity_selection_v3.r")

```

```{r}
#| echo: false

kable(dev_density_df %>% tabyl(B2Risk_Study, mammo_row) %>%  adorn_totals())

sum1 <- mean_density_df %>% 
  group_by(ancat_dmode_v2) %>% 
  summarise(n = n())
kable(sum1)

sum2 <- mean_density_df %>% 
  group_by(ancat_dmode_v2) %>% 
  mean_table(mean_density)
kable(sum2)

# charts 
hist(mean_density_df$mean_density)

boxplot(mean_density_df$mean_density)

# hist by dmode
mean_density_df %>% 
  na.omit() %>% 
  ggplot(aes(x = mean_density, fill = ancat_dmode_v2)) +
  geom_histogram(binwidth = 10) +
  facet_wrap(~ ancat_dmode_v2) +  # Separate histograms for each group
  coord_cartesian(xlim = c(0, 100),
                  ylim = c(0, 200)) +  
  theme_classic()

# 
# box plots with jitter
mean_density_df %>% 
  ggplot(aes(x = ancat_dmode_v2, y = mean_density, fill = ancat_dmode_v2)) +
  geom_jitter(position = position_jitter(width = 0.2), 
              alpha = 0.2,
              colour = "grey50") +
  geom_boxplot(alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()


# comparison with b2 risk density

b2_density_df <- dev_density_df %>% 
  group_by(tcode) %>% 
  arrange(tcode, MammoDat_f) %>% 
  filter(B2Risk_Study == "Y") %>% 
  mutate(B2mean_density = mean(Density_Reading),
         B2SD_density = SD(Density_Reading)
  ) %>% 
  select(tcode, B2mean_density, B2SD_density) %>% 
  distinct() %>% 
  ungroup()


comp_density <- mean_density_df %>% 
  full_join(b2_density_df, by = "tcode") %>% 
   mutate(diff = mean_density - B2mean_density)

hist(comp_density$diff)

comp_density %>% 
  mean_table(mean_density) 

comp_density %>% 
  mean_table(B2mean_density) 
```
