---
title: "Case selection comparison"
author: "M Brayley"
format: html
editor: visual
---

```{r}
#| echo: false

# comparison of case selection by brca flag (originally used by Louise) and the new reproducible selection 


original_cases <- casummary_im %>% 
  filter(First_inv_insitu_Brca == 1,
         incident == 1,
         confirmed == 1)

# n = 4245 

4245 - 4172 # 73


original_cases_ids <- original_cases %>% 
  mutate(reginfo_groupdatesite = as.factor(Reginfo_GroupDateSite),
         reginfo_clusterino = as.factor(Reginfo_Clusterino),
         report_cluster = as.factor(Report_Cluster),
         report_groupdatesite = as.factor(Report_GroupDateSite)) %>% 
  select(tcode, reginfo_groupdatesite, reginfo_clusterino, report_groupdatesite, report_cluster) %>% 
  mutate(original_flag = "Y")

str(cases)
str(original_cases_ids)

cases_comp <- cases %>% 
  full_join(original_cases_ids, by = c("tcode", "reginfo_groupdatesite",
                                       "reginfo_clusterino",
                                       "report_groupdatesite",
                                       "report_cluster") )

kable(cases_comp %>% tabyl(original_flag))

# case ID comparison only (excluding reg and rep variables)

original_ids <- original_cases_ids %>% 
  select(tcode) %>% 
  mutate(original = "Y")

ids <- cases %>% 
  select(tcode) %>% 
  mutate(new = "Y")

id_comp <- ids %>% 
  full_join(original_ids, by = "tcode") %>% 
  mutate(case_selection = as.factor(case_when(original == "Y" & new == "Y" ~ "both",
                          original == "Y" & is.na(new) ~ "original",
                          is.na(original) & new == "Y" ~ "new",
                          TRUE ~ NA)))

tab <- id_comp %>% tabyl(case_selection) %>% 
  adorn_totals() 

kable(tab)

```

## Notes on differences in case selection

e.g. ID T264C624 - this ID was not selected in the new case selection process but was selected in the First_inv_insitu_Brca.

This ID has 2 cancer (BC) records around the same date. The first record is unconfirmed DCIS and the second records is confirmed invasive. The First_inv_insitu_Brca flagged the second row as the first invasive or insitu cancer which seems correct as that is the confirmed one. The new process did not select this row because one of the selection criteria is that the cancer should be confirmed and the first breast cancer. Flag variable indicating first BC was created (according to Michael's original code). However, because this ID has the first cancer unconfirmed, the invasive confirmed entry is flagged as 2nd breast cancer and therefore is not selected.

Do we need to incorporate the confirmed flag into the new case selection? When there is a cluster around the same date and only 1 is confirmed, these cases would not be picked up if the confirmed cancer is not the first in order.
