---
title: "Descriptives"
author: "MB"
format: 
  html: 
    embed-resources: true
editor: visual
---

```{r}
#| include: false
#| echo: false

library(huxtable)
library(gtsummary)
library(survey)

# needed for scripts 1 to 7
source("C:/Users/MBrayley/OneDrive - The Institute of Cancer Research/Work/GitHub/BC_detection_mode/Martina/code/master.R")

```

# Descriptive tables by mode of detection

## Tumour characteristics

```{r}
##| echo: false

# create a dataset with tumour characteristics

tc_df <- an_df %>% 
  select(d_dmode, d_inv_status_lab, diagage, d_grade_lab, d_morph7_lab, d_pos_nodes_lab, d_tumour_size_lab, d_er_status_lab, d_pr_status_lab, d_her2_status_lab) %>% 
  ungroup()

# create tbl summary
tc_df %>% 
  tbl_summary(
    by = d_dmode, 
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p})"
      ),
    digits = all_continuous() ~ 2,
    label = c(d_inv_status_lab ~ "Invasive status",
              diagage ~ "Age at diagnosis",
              d_grade_lab ~ "Grade",
              d_morph7_lab ~ "Morphology",
              d_pos_nodes_lab ~ "Positive nodes",
              d_tumour_size_lab ~ "Tumour size",
              d_er_status_lab ~ "ER status",
              d_pr_status_lab ~ "PR status",
              d_her2_status_lab ~ "HER2 status")
        
  ) 



```

## Risk factors

```{r}
#| echo: false


rf_df <- an_df %>% 
  select(d_dmode, d_R1toBC_lab, d_R1toBC_y, d_R1toMD_y, d_MDtoBC_lab, d_MDtoBC_y, 
         d_R1alcohol_status_lab, d_R1alcohol_units_lab, d_R1smokingstatus_lab,
         d_bmi_entry_lab,d_R1physmet_leis_who_lab,
         d_bbd_lab, d_fambrcaN_lab,
         d_age_menarche_lab, d_ocstatus_lab,
         d_R1menopause_lab3, d_age_menopause_lab, d_R1hrtstatus_lab, 
         d_parous_lab, d_parity_lab, d_agebirth1_lab) %>% 
  ungroup()

# create tbl summary
rf_df %>% 
  tbl_summary(
    by = d_dmode, 
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p})"
      ),
    digits = all_continuous() ~ 2,
    label = c(d_R1toBC_lab ~ "Time from entry to diagnosis (cat)",
              d_R1toBC_y ~ "Time from entry to diagnosis (years)",
              d_R1toMD_y ~ "Time between entry and mammo image (years)",
              d_MDtoBC_lab ~ "Time between mammo and diagnosis (cat)",
              d_MDtoBC_y ~ "Time between mammo and diagnosis (years)",
              d_R1alcohol_status_lab ~ "Alcohol status",
              d_R1alcohol_units_lab ~ "Alcohol units",
              d_R1smokingstatus_lab ~ "Smoking status",
              d_bmi_entry_lab ~ "BMI",
              d_R1physmet_leis_who_lab ~ "Physical Activity (WHO cat)",
              d_bbd_lab ~ "Benign breast disease",
              d_fambrcaN_lab ~ "Family history of BC",
              d_age_menarche_lab ~ "Age at menarche",
              d_ocstatus_lab ~ "Oral contraceptives status",
              d_R1menopause_lab3 ~ "Menopause",
              d_age_menopause_lab ~ "Age at menopause",
              d_R1hrtstatus_lab ~ "HRT status",
              d_parous_lab ~ "Parous",
              d_parity_lab ~ "N of parous pregnancies",
              d_agebirth1_lab ~ "Age at first birth")
        
  ) 
```

## Comparison of trick variables with actual variables

### Tumour characteristics

```{r}
# create a dataset with tumour characteristics

tc_trick_df <- an_df %>% 
  select(d_dmode, d_inv_status_lab, diagage, d_grade_lab, d_grade_tr, d_morph7_lab, d_morph7_tr_lab, d_pos_nodes_lab, d_pos_nodes_tr_lab, d_tumour_size_lab, d_tmsize_tr_lab, d_er_status_lab, d_er_tr_lab, d_pr_status_lab, d_pr_tr_lab, d_her2_status_lab, d_her2_tr_lab) %>% 
  ungroup()

# create tbl summary
tc_trick_df %>% 
  tbl_summary(
    by = d_dmode, 
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p})"
      ),
    digits = all_continuous() ~ 2,
    label = c(d_inv_status_lab ~ "Invasive status",
              diagage ~ "Age at diagnosis",
              d_grade_lab ~ "Grade",
              d_morph7_lab ~ "Morphology",
              d_pos_nodes_lab ~ "Positive nodes",
              d_tumour_size_lab ~ "Tumour size",
              d_er_status_lab ~ "ER status",
              d_pr_status_lab ~ "PR status",
              d_her2_status_lab ~ "HER2 status")
        
  ) 
```

### Parity related

```{r}
#| echo: false


par_df <- an_df %>% 
  select(d_dmode,
         d_parous_lab, d_parity_lab, d_parity_tr_lab, d_agebirth1_lab, d_agebirth1_tr_lab) %>% 
  ungroup()

# create tbl summary
par_df %>% 
  tbl_summary(
    by = d_dmode, 
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p})"
      ),
    digits = all_continuous() ~ 2,
    label = c(
              d_parous_lab ~ "Parous",
              d_parity_lab ~ "N of parous pregnancies",
              d_agebirth1_lab ~ "Age at first birth")
        
  ) 


```

### Menopause related 

```{r}
#| echo: false


meno_df <- an_df %>% 
  select(d_dmode, d_ocstatus_lab, d_oc_tr_lab,
         d_R1menopause_lab3, d_age_menopause_lab, d_R1hrtstatus_lab, 
         ) 

# create tbl summary
meno_df %>% 
  tbl_summary(
    by = d_dmode, 
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p})"
      ),
    digits = all_continuous() ~ 2,
    label = c(
              d_ocstatus_lab ~ "Oral contraceptives status",
              d_R1menopause_lab3 ~ "Menopause",
              d_age_menopause_lab ~ "Age at menopause",
              d_R1hrtstatus_lab ~ "HRT status"
              )
        
  ) 
```
